FROM ghcr.io/graalvm/native-image-community:21 as graalvm

COPY . /home/app/http4k
WORKDIR /home/app/http4k

RUN native-image --static --no-fallback -cp build/libs/rinha-0.0.1.jar io.rinha.RinhaKt

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/http4k/io.rinha.rinhakt /app/http4k
ENTRYPOINT ["/app/http4k"]